bugfix in example(generating random domain)
Domains.getRandomDomain() returns an Domain object.
It does not override toString(), so
"thisismychoice@"+Domains.getRandomDomain() will be like
thisismychoice@me.shivzee.util.Domain@7fb4f2a9
This cause following Exception :
javax.security.auth.login.LoginException: Something went wrong while
creating account! Try Againjavax.security.auth.login.LoginException:
Account Already Exists! Error 422
	at me.shivzee.util.JMailBuilder.createAndLogin(JMailBuilder.java:94)

To fix this, I called getDomainName() to get real domain name, and it
worked fine. :)