upstream (#10)
* Update README.md

* Update README.md

* Update README.md

* Update README.md

* ignore eclipse project file

* bugfix in example(generating random domain)

Domains.getRandomDomain() returns an Domain object.
It does not override toString(), so
"thisismychoice@"+Domains.getRandomDomain() will be like
thisismychoice@me.shivzee.util.Domain@7fb4f2a9
This cause following Exception :
javax.security.auth.login.LoginException: Something went wrong while
creating account! Try Againjavax.security.auth.login.LoginException:
Account Already Exists! Error 422
	at me.shivzee.util.JMailBuilder.createAndLogin(JMailBuilder.java:94)

To fix this, I called getDomainName() to get real domain name, and it
worked fine. :)

* add .gitignore for eclipse

Sorry, since I'm in army, all  I can use in here is just Eclipse
Portable XD

* FunctionalInterface annotation because a lambda can be WorkCallback

* add Synchronous methods

* name Threads

* change version number

* fixed pr3

Added Reusability of Code & Updated Java Docs

* Updated Version

* Update README.md

* Added EventListener

* Fix:Patch Request

* Added Checks

* Added: EventListener

* Fix: Naming Convention

* Removed Old Docs

* Added EventListener

* Update: Docs

* Update: EventListener

* Update: Java Docs

* Update: Version

* Add: JMailTM.jar

* Update README.md

* Added: onAccountUpdate Event

* Update: Bind to Logger

* Fixed: Documentation

* Updated: Documentation

* Updated: Version

* Updated: Version

* 1. Added status code 429 Exception
2. Added created/updated time in ZonedDateTime format

* Updated as per comment

* Updated: Version

* Added: Examples Directory

* Added: Login with Token

* Updated: JavaDocs

* Update README.md

* Added if condition for hasAttachments (#6)

* Added if condition for hasAttachments

* As per review comments, modified the if block to minimal

---------

Co-authored-by: aarahman <aarahman@tekion.com>

* Null checks on fields (#7)

* Added if condition for hasAttachments

* Added safeEval() so that if any field is null calling toString will not cause issue

* Changed the primitive data type to Wrapper type in POJO classes

---------

Co-authored-by: aarahman <aarahman@tekion.com>

* Update readme tags

---------

Co-authored-by: awidesky <awidesky@naver.com>
Co-authored-by: VigneshwaranT <vigneshwarant@tekion.com>
Co-authored-by: Ahamed Abdul Rahman <ahamedabdulrahman@gmail.com>
Co-authored-by: aarahman <aarahman@tekion.com>